### PR TITLE
Fix issue where a commit could yield a result breaking connect async.waterfall

### PR DESCRIPTION
**Pull request by hyperlink**

### CODE REVIEW

**Comment by aikar** [comment]
@hyperlink how is this an issue? the next function doesn't even consume the input.

It would just be discarded. The only thing I see this change doing is dropping whatever the commit responded with and sending null instead.

But since the next function doesn't consume the previous response, how does that change anything?

**Comment by aikar** [comment]
Ohh... I think I see what you are trying to do, but you put this change at the wrong place.

I think you were meaning if the self.options.onRebalance yields a response ,the next auto commit signature would need to be function (foo, callback) { }

Which would make the current callback parameter be in the wrong location.

So yeah I see what the 'issue' is, but this PR put the change in the wrong place.

**Comment by aikar** [comment]
actually hmm i guess that does apply here too. I don't know why I didn't run into this issue myself. 

So this change is needed as you have it, but you also need to apply it to the onRebalance call, as that is 'userland' and undefined on how the implementor will return.

**Comment by hyperlink** [comment]
@aikar yes we should wrap the `onRebalance` callback as well.

**Comment by aikar** [comment]
and conveniently, this issue hit me in production today...!

**Pull request merged**
