### PR TITLE
Custom partitioner

### PR DESCRIPTION
**Pull request by bkim54**
addresses #619

### CODE REVIEW

**Comment by bkim54** [comment]
@hyperlink I also updated the typings for kafka-node to reflect the changes in this PR, could you approve that as well? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14911

Thanks!

**Comment by bkim54** [comment]
@hyperlink wouldnt it also be confusing to override the provided partitioners? 

By providing a CustomPartitionerType the code is more self documenting than using  a `partitionerType` called "default" that uses a user provided getPartition function

**Comment by hyperlink** [comment]
@bkim54 I'm looking at it from the perspective of the module user. So far the user of the module is only exposed to the concepts of partitioner through the `partitionerType`.  With the code as is to add their own implementation requires them remember to change two things versus a single thing of adding a new argument. To me the later is simpler.

**Comment by bkim54** [comment]
why then even provide the concept of `partitionerType`?

Wouldnt it then be better to have one "default partitioner" (a cyclic partitioner is probably the best default) and letting the user pass in a getPartition function

**Comment by hyperlink** [comment]
@bkim54 are you suggesting `partitionerType` could not only take 1, 2, 3 but also a function which would override the built in partitioners?

**Comment by bkim54** [comment]
@hyperlink, no im suggesting providing one default partitioner type and giving users the ability to override the partitioner. (Similar to how the java client works).

**Comment by hyperlink** [comment]
Ok @bkim54 then could we address my initial concern regarding potential user error by throwing an exception if `partitionerType` is not 4 and a custom partitioner function was passed in?

Thanks!

**Comment by bkim54** [comment]
@hyperlink thanks for working through this with me! 😃

**Comment by hyperlink** [comment]
heh np.

**Pull request merged**
