### PR TITLE
Race condition when closing client, still attempt to refreshBrokerMetadata when client is closing

### PR DESCRIPTION
**Pull request by HansonHH**
I've filed an issue regarding this commit, please refer to #1045. There is a race condition when broker is disconnecting and Kafka client sometimes still attempts to refreshBrokerMetadata when client is closing.

### CODE REVIEW

**Comment by aikar** [comment]
OH man this may be one of the missing pieces of my https://github.com/SOHU-Co/kafka-node/pull/907 PR.

I'm all for this landing/being merged separate from my PR though as I'm still working on test failures for it, but I'll pull this to my local fork and should hopefully finally fix the hangs I still occasionally get!

**Comment by aikar** [comment]
Interesting state of this PR, it seems like you have some commits  for IPv6, that shows up in https://patch-diff.githubusercontent.com/raw/SOHU-Co/kafka-node/pull/1048.patch, but doesn't in the diff view...

So confused on what's going on there heh.

**Comment by HansonHH** [comment]
@aikar Previously, I had a PR fix for IPv6 support and that commit got merged into master branch.

**Comment by hyperlink** [comment]
Published as 3.0.0

**Pull request merged**
