### PR TITLE
Consumer stream

### PR DESCRIPTION
**Pull request by lliss**
Designed to solve #371, this change reimplements the processing of data as a stream in such a way that back pressure should not cause dropped messages. The change is designed to be fully backwards compatible.

### CODE REVIEW

**Comment by lliss** [comment]
@hyperlink Is it normal to see sporadic test failures? Locally and via travis, we're seeing intermittent issues with brokers not being available.

**Comment by hyperlink** [comment]
Thanks for the PR @lliss!

Could you add some documentation and examples on using the stream?

Regarding the tests I'm seeing the failures happen more often now that the tests run against different kafka versions though I haven't had a chance to investigate it.

**Comment by hyperlink** [comment]
@lliss if you rebase you'll find the tests to be more stable. I will look at this PR in more detail soon.

**Comment by hyperlink** [comment]
Thanks for your contribution. Closing this PR since this is continued in #732 any discussions can done in that PR.

**Pull request closed without merging**
