### PR TITLE
High level consumers should be able to recover a zk disconnect

### LINKED ISSUE #279: kafka-node does not recover from a network interruption with Zookeeper
## Test setup

Please see issue #277 for details on how to set up your environment for this test.

## Steps to reproduce

* Start the kafka console producer to send messages
`./bin/kafka-console-producer.sh --broker-list 192.168.99.100:9092 --topic KafkaConnectivityTest`
* Run `./kafkatest.js`
* Send a test message through the producer console and verify a message show up
* Shell to the docker zookeeper container `docker exec -it kafkanode_zookeeper_1 bash`
* In the container execute `iptables -A INPUT -s "192.168.99.1" -j REJECT; iptables -A OUTPUT -s "192.168.99.1" -j REJECT;`
* Verify the record is in iptables `iptables -nvL`
* Verify from your machine that port is no longer open `nmap -p 2181 192.168.99.100`
* Wait at least 30 seconds
* Remove the rule by executing `iptables -D INPUT -s "192.168.99.1" -j REJECT; iptables -D OUTPUT -s "192.168.99.1" -j REJECT;` in the zookeeper container
* Expect to see below errors

```
an error happened { [FailedToRegisterConsumerError: Exception: CONNECTION_LOSS[-4]] message: 'Exception: CONNECTION_LOSS[-4]' }
  kafka-node:zookeeper CONNECTION_LOSS: Exception: CONNECTION_LOSS[-4]
    at ConnectionManager.cleanupPendingQueue (/Users/xiaoxin.lu/dev/kafka-node/node_modules/node-zookeeper-client/lib/ConnectionManager.js:189:46)
    at ConnectionManager.onSocketClosed (/Users/xiaoxin.lu/dev/kafka-node/node_modules/node-zookeeper-client/lib/ConnectionManager.js:274:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:468:12) +1m
an error happened { [CONNECTION_LOSS: Exception: CONNECTION_LOSS[-4]]
  code: -4,
  name: 'CONNECTION_LOSS',
  path: undefined,
  message: 'Exception: CONNECTION_LOSS[-4]' }
an error happened { [CONNECTION_LOSS: Exception: CONNECTION_LOSS[-4]]
  code: -4,
  name: 'CONNECTION_LOSS',
  path: undefined,
  message: 'Exception: CONNECTION_LOSS[-4]' }
an error happened { [FailedToRegisterConsumerError: Exception: CONNECTION_LOSS[-4]] message: 'Exception: CONNECTION_LOSS[-4]' }
an error happened { [FailedToRegisterConsumerError: Exception: CONNECTION_LOSS[-4]] message: 'Exception: CONNECTION_LOSS[-4]' }
an error happened { [FailedToRegisterConsumerError: Exception: CONNECTION_LOSS[-4]] message: 'Exception: CONNECTION_LOSS[-4]' }
```

* Verify from your machine that port is open again `nmap -p 2181 192.168.99.100`
* Send a test message from console producer and expect to see the message show up. This is good however connection with zookeeper is severed and did not recover. We think this is a problem.

I am looking into this issue and hopefully will have a PR fix soon.

### PR DESCRIPTION
**Pull request by hyperlink**
This PR is to fix #279

### CODE REVIEW

**Comment by nayalin** [comment]
Hi,
I am also experiencing the same issue, I would like to know what is the status and when would it be merged with master?

Thanks a bunch guys!

**Comment by GonzaloGutierrezMartinMaestro** [comment]
Hi,
I still having the same issue with version 0.3.2
It's this fix in the version 0.3.2?
I get this trace:
{
  "date": "Mon Mar 28 2016 08:56:00 GMT+0000 (UTC)",
  "process": {
    "pid": 13001,
    "uid": 0,
    "gid": 0,
    "cwd": "/opt/timeline",
    "execPath": "/usr/local/bin/node",
    "version": "v5.8.0",
    "argv": [
      "/usr/local/bin/node",
      "/opt/timeline/src/index.js"
    ],
    "memoryUsage": {
      "rss": 146669568,
      "heapTotal": 76627232,
      "heapUsed": 32355224
    }
  },
  "os": {
    "loadavg": [
      1.2470703125,
      1.48974609375,
      1.39697265625
    ],
    "uptime": 14924063
  },
  "trace": [
    {
      "column": 46,
      "file": "/opt/timeline/node_modules/node-zookeeper-client/lib/ConnectionManager.js",
      "function": "ConnectionManager.cleanupPendingQueue",
      "line": 189,
      "method": "cleanupPendingQueue",
      "native": false
    },
    {
      "column": 10,
      "file": "/opt/timeline/node_modules/node-zookeeper-client/lib/ConnectionManager.js",
      "function": "ConnectionManager.onSocketClosed",
      "line": 274,
      "method": "onSocketClosed",
      "native": false
    },
    {
      "column": 13,
      "file": "events.js",
      "function": "emitOne",
      "line": 90,
      "method": null,
      "native": false
    },
    {
      "column": 7,
      "file": "events.js",
      "function": "Socket.emit",
      "line": 182,
      "method": "emit",
      "native": false
    },
    {
      "column": 12,
      "file": "net.js",
      "function": "TCP._onclose",
      "line": 475,
      "method": "_onclose",
      "native": false
    }
  ],
  "stack": [
    "CONNECTION_LOSS: Exception: CONNECTION_LOSS[-4]",
    "    at ConnectionManager.cleanupPendingQueue (/opt/timeline/node_modules/node-zookeeper-client/lib/ConnectionManager.js:189:46)",
    "    at ConnectionManager.onSocketClosed (/opt/timeline/node_modules/node-zookeeper-client/lib/ConnectionManager.js:274:10)",
    "    at emitOne (events.js:90:13)",
    "    at Socket.emit (events.js:182:7)",
    "    at TCP._onclose (net.js:475:12)"
  ],
  "level": "error",
  "message": "uncaughtException: Exception: CONNECTION_LOSS[-4]",
  "timestamp": "2016-03-28T08:56:00.113Z"
}

Thanks

**Comment by panlilu** [comment]
@GonzaloGutierrezMartinMaestro +1

events.js:141
      throw er; // Unhandled 'error' event
      ^
FailedToRegisterConsumerError: Exception: CONNECTION_LOSS[-4]

**Comment by Gowtham95india** [comment]
Is it fixed?

**Comment by hyperlink** [comment]
yes @GonzaloGutierrezMartinMaestro afaik. Though you should switch to using `ConsumerGroup` is possible.

**Comment by Gowtham95india** [comment]
@hyperlink , I'm using consumerGroup. Still getting connection lost error. Any suggestions ?

**Comment by hyperlink** [comment]
Since ConsumerGroup connects to kafka directly to coordinate it shouldn't be getting any connection_loss rebalance errors.

**Comment by respinha-ribeiro** [comment]
@hyperlink we experienced this connection loss error using normal Consumers. 
1) Has this issue been fixed also for normal consumers?
2) If not, is it even advisable to use them or should we switch to consumer groups in production environments?

**Comment by hyperlink** [comment]
@respinha-ribeiro I did my best to fix this issue two years ago. Since `CONNECTION_LOSS` is zookeeper based error so using `ConsumeGroup` with kafkaHost option will avoid this particular issue.

**Comment by respinha-ribeiro** [comment]
But this PR also handles Zookeeper abrupt connection closing situations, right? 
So, if we want to still use Zookeeper to manage Kafka brokers on a high level consumer / ConsumerGroup in theory we can simply omit the Kafka host, and the client should attempt to reconnect upon error, right?

**Comment by hyperlink** [comment]
@respinha-ribeiro the `Client` should reconnect to zk upon error and the `KafkaClient` should not connect to zookeeper at all since it's a kafka only client. Specifying a kafkaHost in the ConsumerGroup will default to using `KafkaClient`. Hope that answered your question.

**Pull request merged**
