### PR TITLE
Retry failed initial metadata fetches (closes #903)

### LINKED ISSUE #903: "loadMetadataForTopics after connect failed" kills client?
## Bug Report

Maybe something of a design question: should this perhaps disconnect and retry after emitting an error? Or are errors assumed to be permanent & unrecoverable?

https://github.com/SOHU-Co/kafka-node/blob/e7b08646080fc0620a434ecea159e2823e4690c6/lib/kafkaClient.js#L144-L145

When we hit this code the consumer is effectively stopped in its tracks. I think we can work around it, but feels like something kafka-node might be able to take care of for us.

### Environment

* Node version: 8.x
* Kafka-node version: 2.4.1
* Kafka version: 1.0.0

### For specific cases also provide
* Number of Brokers: 1
* Number partitions for topic: N/A

### Include Sample Code to reproduce behavior

I effectively started a Kafka broker, then in a separate terminal ran the following loop to make it perform terribly:

```
while true; do kill -STOP $KAFKA_PID; sleep 0.2; kill -CONT $KAFKA_PID; done
```

(Blunt, but it works!)

Then I kicked off the repro program (may take a few tries to trigger the right error):

```js
const kafka = require('kafka-node')

const group = new kafka.ConsumerGroup({
  kafkaHost: 'localhost:9092',
  groupId: 'example-group',
  sessionTimeout: 6000,
}, 'repro-topic')
group.on('error', err => {
  console.log(err)
})
group.on('message', msg => {
  console.log(msg)
})

process.on('INT', () => {
  group.close(() => {
    process.exit(0)
  })
})
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

```
$ DEBUG=kafka-node:* npm run dev

> kafka-repro@0.0.1 dev /Users/tom/local-src/kafka-repro
> node index.js

  kafka-node:KafkaClient Connect attempt 1 +0ms
  kafka-node:KafkaClient Trying to connect to host: localhost port: 9092 +3ms
  kafka-node:KafkaClient Sending versions request to localhost:9092 +15ms
  kafka-node:KafkaClient broker socket connected {"host":"localhost","port":"9092"} +3ms
  kafka-node:KafkaClient getApiVersions request timedout probably less than 0.10 using base support +502ms
  kafka-node:KafkaClient setting api support to {"produce":{"min":0,"max":1,"usable":1},"fetch":{"min":0,"max":0,"usable":0},"offset":{"min":0,"max":0,"usable":0},"metadata":{"min":0,"max":0,"usable":0},"leader":null,"stopReplica":null,"updateMetadata":null,"controlledShutdown":null,"offsetCommit":{"min":0,"max":2,"usable":2},"offsetFetch":{"min":0,"max":1,"usable":1},"groupCoordinator":{"min":0,"max":0,"usable":0},"joinGroup":{"min":0,"max":0,"usable":0},"heartbeat":{"min":0,"max":0,"usable":0},"leaveGroup":{"min":0,"max":0,"usable":0},"syncGroup":{"min":0,"max":0,"usable":0},"describeGroups":{"min":0,"max":0,"usable":0},"listGroups":{"min":0,"max":0,"usable":0},"saslHandshake":null,"apiVersions":{"min":0,"max":0,"usable":0},"createTopics":null,"deleteTopics":null} +0ms
  kafka-node:KafkaClient loadMetadataForTopics after connect failed { TimeoutError: Request timed out after 30000ms
    at new TimeoutError (/Users/tom/local-src/kafka-repro/node_modules/kafka-node/lib/errors/TimeoutError.js:6:9)
    at Timeout.setTimeout (/Users/tom/local-src/kafka-repro/node_modules/kafka-node/lib/kafkaClient.js:389:14)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) message: 'Request timed out after 30000ms' } +30s
  kafka-node:ConsumerGroup Error from kafka-node-client { TimeoutError: Request timed out after 30000ms
    at new TimeoutError (/Users/tom/local-src/kafka-repro/node_modules/kafka-node/lib/errors/TimeoutError.js:6:9)
    at Timeout.setTimeout (/Users/tom/local-src/kafka-repro/node_modules/kafka-node/lib/kafkaClient.js:389:14)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) message: 'Request timed out after 30000ms' } +7ms
{ TimeoutError: Request timed out after 30000ms
    at new TimeoutError (/Users/tom/local-src/kafka-repro/node_modules/kafka-node/lib/errors/TimeoutError.js:6:9)
    at Timeout.setTimeout (/Users/tom/local-src/kafka-repro/node_modules/kafka-node/lib/kafkaClient.js:389:14)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) message: 'Request timed out after 30000ms' }
```

At this point we see no more output and the consumer/client is effectively "broken".

### PR DESCRIPTION
**Pull request by thomaslee**

### CODE REVIEW

**Comment by thomaslee** [comment]
@hyperlink I've probably got more work to do to get tests passing etc., but hopefully this seems like a reasonable approach.

**Comment by aikar** [comment]
since everything else passed, i think it was a fluke timeout test.

the tests on this project are not durable and constantly have false positives.

**Comment by thomaslee** [comment]
Yeah all those builds were various minor rebases etc. -- I saw it fail somewhere new each time, on different configurations. 😃

**Comment by hyperlink** [comment]
Wouldn't this implementation keep the client stuck trying to loadingMetadata on the same bad kafka broker forever?

**Comment by aikar** [comment]
@hyperlink good catch, maybe should go back to the retry root and start whole process over again so it can switch to a different broker.

**Pull request closed without merging**
