### PR TITLE
Fix client socket when closing and error handling

### LINKED ISSUE #300: Consumer stops consuming
I have problem with consuming messages after PR #262. Consumer consumes 24000 messages (single FetchResponse) and does not consume any more messages. It works with 9405c86.

### LINKED ISSUE #311: Consumer stops consuming after initial messages
I can only get kafka-node to read events that were created while the consumer was offline.

I have 3 terminal windows open:
1: A small application using kafka-node's Producer to send messages every 1 second to a topic with 1 partition.
2: Running `kafka-console-consumer.sh --zookeeper localhost --topic testTopic`
3: Running `node kafka-node/examples/consumer.js --topic=testTopic`.  Removed line 12.

The kafka-console-consumer receives every message.  The kafka-node consumer.js does not receive any messages.  When I close and re-open it, then it will receive all of the messages since the last restart, but no more until I close and re-open it again.

Using Node v4.2.4 on OS X 10.11.2.  Installed kafka with homebrew.

### LINKED ISSUE #313: Not reading from queue
With `kafka-node@0.3.1` I cannot get the library to consume messages. With older versions of kafka-node this sample app works. I looked at the issues in github and this might be related to #311. I git-bisected and the following commit is the blocker:

```
commit fcce260e24d8cc6071ed3092eb51fccda039838b
Author: Carles Sistare <snip>
Date:   Sun Oct 25 14:08:55 2015 +0100

    Buffer batch for async producers

    Other kafka connectors such as the Java one have the possibility to configurate an optional batch (client-side) for async producer mode, in order to send batches of messages instead of single messages at time. This increases performance because the kafka server doesnt need to answer ACK at every message.

    The options are:
    - Batch size in bytes
    - Batch age in miliseconds
```

Sample App:
```javascript
'use strict';

var kafka = require('kafka-node');
var Consumer = kafka.Consumer;
var Offset = kafka.Offset;
var Client = kafka.Client;
var argv = require('optimist').argv;
var topic = argv.topic || 'observations.json';

var client = new Client('zkserver:2181/chroot');
var topics = [
      {topic: topic, partition: 0, time: -2}
    ],
    options = { autoCommit: false, fetchMaxWaitMs: 1000, fetchMaxBytes: 1024*1024 };

var consumer = new Consumer(client, topics, options);
var offset = new Offset(client);

var message_count = 0;
var start_time = Date.now() / 1000;

function stop() {
  var end_time = Date.now() / 1000;
  console.log('Processed ' + message_count + ' messages');
  console.log('Elapsed Time ' + (end_time - start_time));
  console.log('TPS: ' + message_count / (end_time - start_time));
  process.exit(0);
}

process.on('SIGINT', stop);
setTimeout(stop, 20000);

consumer.on('message', function (message) {
  message_count++;
  console.log(message);
});


consumer.on('error', function (err) {
  console.log('error', err);
});

/*
* If consumer get `offsetOutOfRange` event, fetch data from the smallest(oldest) offset
*/
consumer.on('offsetOutOfRange', function (topic) {
    console.log('offsetOutOfRange');
    offset.fetch([topic], function (err, offsets) {
      var min = Math.min.apply(null, offsets[topic.topic][topic.partition]);
      consumer.setOffset(topic.topic, topic.partition, min);
    });
});
```

### PR DESCRIPTION
**Pull request by carlessistare**
resolve #313 resolve #311 resolve #300 
Fix on error handling after PR #262

### CODE REVIEW

**Comment by rphillips** [comment]
+1

**Comment by groundwater** [comment]
I had problems like #313 and #311 and this sesms to fix it.

Thank you for your hard work!

**Comment by carlessistare** [comment]
I'll try to do a PR adding and fixing old unit tests. It's becoming
impossible to know if you break something, every time that we add some
functionality.

Le lun. 18 janv. 2016 23:55, Jacob Groundwater <notifications@github.com> a
écrit :

**Comment by cmacnaughton-al** [comment]
+1!  Fixed issue for me, many thanks!

**Comment by philippehenin** [comment]
Tested the correction. The Fix seems Ok.

**Comment by serega-ivanov** [comment]
+1

**Comment by hhhonzik** [comment]
+1

**Comment by codyhazelwood** [comment]
+1 This fixes my issues.  Thanks!  It would be great to get this merged!

**Comment by johnfn** [comment]
THANK YOU SO MUCH

**Comment by Babacooll** [comment]
Could this be merged anytime soon? :)

**Comment by carlessistare** [comment]
@haio is there a way for this pr to be merge soon?

**Comment by nandanrao** [comment]
Using this branch, if I kill my broker while the client is connect, I get the following error (I'm not at all familiar with the codebase, but I assume it just needs another level of defensive checking):

Happy to play around on a branch, unless you feel like you know exactly what to do with this, @carlessistare?

```
if (!broker.socket || broker.socket.error) {
               ^
TypeError: Cannot read property 'socket' of undefined
    at Client.loadMetadataForTopics (/Users/nandanrao/Documents/Relink/parse/node_modules/kafka-node/lib/client.js:234:16)
    at RetryOperation._fn (/Users/nandanrao/Documents/Relink/parse/node_modules/kafka-node/lib/client.js:358:18)
    at RetryOperation.attempt (/Users/nandanrao/Documents/Relink/parse/node_modules/kafka-node/node_modules/retry/lib/retry_operation.js:56:8)
    at attemptRequestMetadata (/Users/nandanrao/Documents/Relink/parse/node_modules/kafka-node/lib/client.js:356:19)
    at Client.refreshMetadata (/Users/nandanrao/Documents/Relink/parse/node_modules/kafka-node/lib/client.js:352:5)
    at /Users/nandanrao/Documents/Relink/parse/node_modules/kafka-node/lib/highLevelConsumer.js:173:37
    at /Users/nandanrao/Documents/Relink/parse/node_modules/kafka-node/lib/highLevelConsumer.js:433:17
    at /Users/nandanrao/Documents/Relink/parse/node_modules/kafka-node/node_modules/async/lib/async.js:726:13
```

**Comment by carlessistare** [comment]
Thanks a lot for the input @nandanrao could you show how the procedure for killing the worker? I'd like to reproduce the error, before fixing.
Cheers

**Comment by nandanrao** [comment]
Yeah so I see the same problem in both of these cases:

1) I have a running zookeeper, but no kafka broker connected. I run my node-kafka app, and it breaks in the above-stated way.

2) I have a running zookeeper and a broker connected. I run my node-kafka app, and then I kill the broker. The node-kafka app breaks in the above-stated way.

In both cases, the node-kafka library successfully throws this error, which I catch:

```
BrokerNotAvailableError: Could not find a broker
        at new BrokerNotAvailableError (/Users/nandanrao/Documents/Relink/parse/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:11)
        at Client.brokerForLeader (/Users/nandanrao/Documents/Relink/parse/node_modules/kafka-node/lib/client.js:495:32)
        at Client.loadMetadataForTopics (/Users/nandanrao/Documents/Relink/parse/node_modules/kafka-node/lib/client.js:232:23)
        at Client.send (/Users/nandanrao/Documents/Relink/parse/node_modules/kafka-node/lib/client.js:384:14)
        at Client.sendOffsetCommitRequest (/Users/nandanrao/Documents/Relink/parse/node_modules/kafka-node/lib/client.js:187:10)
        at autoCommit (/Users/nandanrao/Documents/Relink/parse/node_modules/kafka-node/lib/highLevelConsumer.js:489:21)
        at HighLevelConsumer.stop (/Users/nandanrao/Documents/Relink/parse/node_modules/kafka-node/lib/highLevelConsumer.js:588:10)
        at async.series.self.client.zk.getConsumersPerTopic.consumerPerTopicMap (/Users/nandanrao/Documents/Relink/parse/node_modules/kafka-node/lib/highLevelConsumer.js:274:22)
```

But soon after a couple of those are thrown, I get the broker-socket error, which crashes everything. Let me know if you have trouble reproducing!

**Comment by carlessistare** [comment]
Well observed, I'll fix this behaviour as soon as I can

**Comment by nandanrao** [comment]
You're saving my ass @carlessistare, thanks!!

**Comment by carlessistare** [comment]
Hi @nandanrao I admit that I could not get exactly the same error than you, but this should fix your issue f62191f2c61636142c9a818e18789e97878111a4
Does it make things right for you?

**Comment by springuper** [comment]
good job!

**Pull request merged**
