### PR TITLE
Update test to run against docker

### PR DESCRIPTION
**Pull request by hyperlink**
- [x] Update tests to run against dockerized kafka/zookeeper
- [x] Fix flaky tests
- [x] Setup travis CI

### CODE REVIEW

**Comment by hyperlink** [comment]
I had to disable the zookeeper test since multiple brokers do not play well in travis.

**Comment by hyperlink** [comment]
@haio can you turn on Travis CI for this repo? I don't have admin access to this repo.

**Comment by lightswitch05** [comment]
@haio can @hyperlink be given admin access? Having [Travis CI](https://travis-ci.org/) and [Coveralls](https://coveralls.io/) integration would be a great help to this project

**Comment by hyperlink** [comment]
Maybe @crzidea could help us enable Travis ?

**Comment by crzidea** [comment]
@hyperlink Sorry for late. I have enabled Travis, now you can play with it. 
https://travis-ci.org/SOHU-Co/kafka-node

**Pull request merged**
