### PR TITLE
Add eslint

### PR DESCRIPTION
**Pull request by hyperlink**
Hello @estliberitas and @haio ! I think this project can benefit from some style standardization (ie we no longer have to look check for style in our PRs). I picked the [semistandardjs](https://github.com/Flet/semistandard) since the existing codebase was fairly close to it already.

Some of the changes include:
- Changed spacing of the indentation from 4 to 2
- Removed unused vars linter found
- Removed unnecessary `call` and `bind`
- Handle some unhandled error cases

Please give some feedback.

### CODE REVIEW

**Comment by tlenex** [comment]
i recommend using this: http://editorconfig.org/ too

**Comment by estliberitas** [comment]
Nice work @hyperlink ! Sorry for being silent for that big time. Now slowly getting into Github again.

**Comment by hyperlink** [comment]
heh np @estliberitas. We need to get @haio to turn on Travis for this repo.

**Comment by estliberitas** [comment]
@hyperlink I'll try to reach him, it's usually quite difficult hehe.

**Pull request merged**
