### PR TITLE
upgrade snappy depend to 4.0.0

### LINKED ISSUE #241: does not compile with iojs >= 3.0.0 due to snappy version
As per #204, iojs-3.0.0 has a newer version of nan, compiling requires snappy version 4.0.0.

### PR DESCRIPTION
**Pull request by chrishiestand**
2 snappy unit tests still passing after upgrade

close #241

### CODE REVIEW

**Comment by stryju** [comment]
snappy is failing too right now, see https://github.com/kesla/node-snappy/pull/64

**Comment by imsnif** [comment]
+1

**Comment by MayhemYDG** [comment]
@haio
:+1:

**Comment by estliberitas** [comment]
4.0.1 is working

**Comment by haio** [comment]
Thanks!

**Pull request merged**
