### PR TITLE
Bring over TS definition from definitelytyped

### PR DESCRIPTION
**Pull request by priithaamer**
Simply starting out by bringing over TypeScript definitions from DefinitelyTyped. Fixes to definition file will follow it this PR flies.

See #937

### CODE REVIEW

**Comment by zoltan-nz** [comment]
This looks fantastic. Thank you very much. Great job! :)

What do think about moving the `tsconfig.json` inside the `types` folder, where we could have a test file also. Like in the `chalk` project: https://github.com/chalk/chalk/tree/master/types

And we can somehow extend the `npm test` also with `tsc --project types`

**Comment by priithaamer** [comment]
Thanks for the recommendation @zoltan-nz. Copied over tests part from DT and added it to test script.

**Comment by zoltan-nz** [comment]
@priithaamer wow, you were quick, very impressive. Thank you. :)

Looks good to me.

As I see you are an expert in this area. I'm just wondering how would you add the type definition of `ProducerStream`? I tried it, but the compiler expected, that it should be a kind of `WritableStream`, and it became quite messy after that. What do you think?

**Comment by priithaamer** [comment]
Ok I will try it. Haven’t used ProducerStream myself so not super familiar with the api.

**Comment by zoltan-nz** [comment]
@priithaamer finally I figured it out. I just sent a PR to your branch.
https://github.com/priithaamer/kafka-node/pull/1

**Comment by priithaamer** [comment]
@zoltan-nz Nice, thanks! Just had one comment regarding tests. If you are not up to it, i can merge it anyway.

@hyperlink Let me know if anything keeping from merging this.

**Comment by hyperlink** [comment]
@priithaamer should we wait to merge until @zoltan-nz changes have been merged to your branch? And I have very limited knowledge of typescript and not sure how to verify this any tips would be helpful.

**Comment by zoltan-nz** [comment]
@hyperlink @priithaamer Thank you! I try to extend our test coverage also... let see how is it going. :)

**Comment by hyperlink** [comment]
Thank you for your contribution!

**Pull request merged**
