### PR TITLE
Fixed documentation and made autoCommit() force parameter optional.

### PR DESCRIPTION
**Pull request by cedarm**
I'm guessing that force is supposed to be optional.  I'll revise if not.

### CODE REVIEW

**Comment by haio** [comment]
@cedarm could you also fix the problem in low level Consumer, thanks!

**Comment by haio** [comment]
#306 has handled this, so close.

**Comment by mllanes** [comment]
I can't seem to find this PR reflected on the docs

**Comment by cedarm** [comment]
#306 was merged instead of this

**Pull request closed without merging**
