### PR TITLE
KafkaClient should not refresh metadata when broker socket is closed …

### PR DESCRIPTION
**Pull request by hyperlink**
…due to being idle

### CODE REVIEW

**Comment by crobinson42** [comment]
It appears this test fails on all builds in Travis 🔨 
#removeTopics
      1) "after all" hook: close consumer group

https://github.com/SOHU-Co/kafka-node/blob/master/test/test.consumerGroup.js#L1123

**Comment by crobinson42** [comment]
This will cause:

`kafka-node:KafkaClient kafka-node-client to 192.168.0.151:9092 is idle not reconnecting +10m`

What do you think about adding a param to force reconnecting when idle in this scenario?

**Comment by crobinson42** [comment]
Something like `new KafkaClient({ reconnectOnIdle: true })`

**Comment by hyperlink** [comment]
> It appears this test fails on all builds in Travis 🔨
> #removeTopics
> 1) "after all" hook: close consumer group
> 
> https://github.com/SOHU-Co/kafka-node/blob/master/test/test.consumerGroup.js#L1123

Yup that is one of the flaky tests. :unamused:

> Something like `new KafkaClient({ reconnectOnIdle: true })`

Not against adding this. PR?

**Pull request merged**
